package com.bookStore.dao;

import com.bookStore.model.Author;
import com.bookStore.model.AuthorExample;
import java.util.List;

public interface AuthorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int countByExample(AuthorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int deleteByExample(AuthorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int deleteByPrimaryKey(String authorid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    void insert(Author record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    void insertSelective(Author record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    List<Author> selectByExample(AuthorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    Author selectByPrimaryKey(String authorid);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int updateByExampleSelective(Author record, AuthorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int updateByExample(Author record, AuthorExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int updateByPrimaryKeySelective(Author record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Fri May 15 17:14:21 PDT 2015
     */
    int updateByPrimaryKey(Author record);
}