package com.bookStore.daoGenericCI;

import com.bookStore.model.Author;
import com.bookStore.model.AuthorExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class AuthorDAOImpl implements AuthorDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public AuthorDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int countByExample(AuthorExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("author.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int deleteByExample(AuthorExample example) throws SQLException {
        int rows = sqlMapClient.delete("author.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int deleteByPrimaryKey(String authorid) throws SQLException {
        Author key = new Author();
        key.setAuthorid(authorid);
        int rows = sqlMapClient.delete("author.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public void insert(Author record) throws SQLException {
        sqlMapClient.insert("author.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public void insertSelective(Author record) throws SQLException {
        sqlMapClient.insert("author.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Author> selectByExample(AuthorExample example) throws SQLException {
        List<Author> list = sqlMapClient.queryForList("author.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public Author selectByPrimaryKey(String authorid) throws SQLException {
        Author key = new Author();
        key.setAuthorid(authorid);
        Author record = (Author) sqlMapClient.queryForObject("author.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int updateByExampleSelective(Author record, AuthorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("author.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int updateByExample(Author record, AuthorExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("author.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int updateByPrimaryKeySelective(Author record) throws SQLException {
        int rows = sqlMapClient.update("author.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    public int updateByPrimaryKey(Author record) throws SQLException {
        int rows = sqlMapClient.update("author.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    private static class UpdateByExampleParms extends AuthorExample {
        private Object record;

        public UpdateByExampleParms(Object record, AuthorExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}