package com.bookStore.daoGenericCI;

import com.bookStore.model.Author;
import com.bookStore.model.AuthorExample;
import java.sql.SQLException;
import java.util.List;

public interface AuthorDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int countByExample(AuthorExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int deleteByExample(AuthorExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int deleteByPrimaryKey(String authorid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    void insert(Author record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    void insertSelective(Author record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    List<Author> selectByExample(AuthorExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    Author selectByPrimaryKey(String authorid) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int updateByExampleSelective(Author record, AuthorExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int updateByExample(Author record, AuthorExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int updateByPrimaryKeySelective(Author record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table author
     *
     * @ibatorgenerated Mon May 18 12:51:21 PDT 2015
     */
    int updateByPrimaryKey(Author record) throws SQLException;
}