package com.bookStore.model;

public class Author {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column author.authorid
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	private String authorid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column author.authname
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	private String authname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column author.authaddress
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	private String authaddress;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column author.authorid
	 * @return  the value of author.authorid
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public String getAuthorid() {
		return authorid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column author.authorid
	 * @param authorid  the value for author.authorid
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public void setAuthorid(String authorid) {
		this.authorid = authorid == null ? null : authorid.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column author.authname
	 * @return  the value of author.authname
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public String getAuthname() {
		return authname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column author.authname
	 * @param authname  the value for author.authname
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public void setAuthname(String authname) {
		this.authname = authname == null ? null : authname.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column author.authaddress
	 * @return  the value of author.authaddress
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public String getAuthaddress() {
		return authaddress;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column author.authaddress
	 * @param authaddress  the value for author.authaddress
	 * @ibatorgenerated  Mon May 18 12:51:21 PDT 2015
	 */
	public void setAuthaddress(String authaddress) {
		this.authaddress = authaddress == null ? null : authaddress.trim();
	}
}